name: kalion-digital
region: fra
services:
  - name: web
    github:
      branch: master
      deploy_on_push: true
      repo: kalionmaxim/kalion-digital-react
    build_command: npm run build
    run_command: npx serve -s build -l 3000
    environment_slug: node-js
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
